spring:
    application:
        name: user_service
    security:
        user:
            password: 123
        filter:
            order: 10
    datasource:
        url: jdbc:postgresql://postgres-db:5432/userdb
        username: user
        password: 123
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update  
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect  
                show-sql: true  

springdoc:
    api-docs: 
        path: /v3/api-docs
        enabled: true
    swagger-ui: 
        use-root-path: true
        enabled: true

application:
    description:
        "Meditation App"
    version:
        "1.0"

token:
    signing:
        key:
            "d2lsbGlhbS1naWJzb24tbmV1cm9tYW5jZXItaXMtYS1jb29sLWJvb2stZG9udC15b3UtdGhpbmstcXVlc3Rpb25tYXJrLXdpbGxpYW0tZ2lic29uLW5ldXJvbWFuY2VyLWlzLWEtY29vbC1ib29rLWRvbnQteW91LXRoaW5rLXF1ZXN0aW9ubWFyaw=="

logging:
    level: 
        org:
            springframework:
                web: 
                    DEBUG
        com:
            fasterxml:
                jackson:
                    DEBUG


