services:
  user_service:
    image: user_service_image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgres-db
        # condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/userdb  # Use internal port
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=123
    networks:
      - user_service_network

  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: userdb  
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
    ports:
      - "5434:5432"  # Map to the default internal port
    volumes:
      - pgdata:/var/lib/postgresql/data 
    networks:
      - user_service_network
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U userdb"]  # Correct user here
    #   interval: 1s 

networks:
  user_service_network:
    driver: bridge

volumes:
  pgdata:
    driver: local
